import { index, integer, real, sqliteTable, text } from 'drizzle-orm/sqlite-core';

export const requestEvents = sqliteTable('request_events', {
    id: text('id').primaryKey(),
    project_key: text('project_key').notNull(),
    session_id: text('session_id').notNull(),
    url: text('url').notNull(),
    method: text('method').notNull(),
    status_code: integer('status_code'),
    request_size: integer('request_size'),
    response_size: integer('response_size'),
    dns: real('dns'),
    tcp: real('tcp'),
    tls: real('tls'),
    ttfb: real('ttfb'),
    duration: real('duration'),
    page_url: text('page_url'),
    referrer: text('referrer'),
    timestamp: integer('timestamp').notNull(),
    browser: text('browser'),
    browser_version: text('browser_version'),
    os: text('os'),
    os_version: text('os_version'),
    device_type: text('device_type'),
    screen_res: text('screen_res'),
    connection_type: text('connection_type'),
    language: text('language'),
    country: text('country'),
    city: text('city'),
    region: text('region'),
    timezone: text('timezone'),
    isp: text('isp'),
    asn: integer('asn'),
    ip_hash: text('ip_hash'),
}, (t) => [
    index('idx_request_events_project_key').on(t.project_key),
    index('idx_request_events_timestamp').on(t.timestamp),
    index('idx_request_events_project_timestamp').on(t.project_key, t.timestamp),
    index('idx_request_events_project_url').on(t.project_key, t.url),
    index('idx_request_events_project_status').on(t.project_key, t.status_code),
    index('idx_request_events_project_country').on(t.project_key, t.country),
    index('idx_request_events_project_device').on(t.project_key, t.device_type),
    index('idx_request_events_session_id').on(t.session_id),
]);
